### ISSUE TITLE
Pin mapping for Particle Photon 2

### ISSUE THREAD

**Issue by nicowitteman** [pkourany/MFRC522_RFID_Library#10]
Hello Paul,
I like the lib, but it took me some time to connect correctly.

I propose you add this pin mapping to the readme file:

mfrc522 - Photon 2
SDA - S3 (set in code as SS or S3)
SCK - SCK
MOSI - MO
MISO - MI
GND - GND
RST - D2 (configurable)
3.3V - 3.3V

**Comment by pkourany** [comment]
@nicowitteman, the pin assignment for hardware SPI is the same on all Particle devices.  The P2 just doesn't have enough room on the device to show "MOSI" so it shows "MO" for example.  As for the SS and RST pins, those are user-defined anyway.  So, I am not inclined to change the readme since it is just an example.

**Comment by nicowitteman** [comment]
Fair enough
